markdown: redcarpet
highlighter: pygments

defaults: 
  - 
   scope:
     path: ""
   values: 
     layout: "default"
     bannercolor: "grey"
     bannerimage: ""
     maroon: "rgb(136,48,48)"
     title: "luiarthur.github.io"
     author: "Arthur Lui"
     titlesize: "1"
